---
# 服务器信息 (Oracle Cloud & Home Service)
# 参考文档：https://gethomepage.dev/configs/services/
# ICON查询：https://pictogrammers.com/library/mdi/

- 公网服务:
    - Plex:
        icon: mdi-plex
        href: https://plex.homehub.stream:8443/web/index.html#!/
        description: Plex 媒体服务器
        target: _blank
        siteMonitor: https://plex.homehub.stream:8443/
    - 飞牛影视:
        icon: mdi-movie-roll
        href: https://fn.homehub.stream:8443/v
        description: 飞牛OS 影视服务
        target: _blank
        siteMonitor: https://fn.homehub.stream:8443/v
    - Jellyfin:
        icon: mdi-jellyfin
        href: https://tv.homehub.stream:8443/web/#/home.html
        description: 在线影视服务（Jellyfin）
        target: _blank
        siteMonitor: https://tv.homehub.stream:8443
    - MoviePilot:
        icon: mdi-movie-open
        href: https://mp.homehub.stream:8443/
        description: MoviePilot 影音管理
        target: _blank
        siteMonitor: https://mp.homehub.stream:8443
    - 飞牛OS:
        icon: mdi-folder-network-outline
        href: https://fn.homehub.stream:8443/
        description: 飞牛OS 主机管理
        target: _blank
        siteMonitor: https://fn.homehub.stream:8443
    - 1Panel:
        icon: mdi-view-dashboard-variant
        href: https://panel.homehub.stream:8443/astral
        description: 1Panel 管理面板
        target: _blank
        siteMonitor: https://panel.homehub.stream:8443/
    - qBittorrent:
        icon: mdi-qbittorrent
        href: https://qb.homehub.stream:8443
        description: qBittorrent WebUI
        target: _blank
        siteMonitor: https://qb.homehub.stream:8443
    - qBittorrent-刷流:
        icon: mdi-trending-up
        href: https://flush.homehub.stream:8443
        description: 刷流专用 qBittorrent
        target: _blank
        siteMonitor: https://flush.homehub.stream:8443
    - qBittorrent-保种:
        icon: mdi-seed
        href: https://keep.homehub.stream:8443
        description: 保种专用 qBittorrent
        target: _blank
        siteMonitor: https://keep.homehub.stream:8443
    - 青龙面板:
        icon: mdi-script-text
        href: https://ql.homehub.stream:8443/
        description: 定时任务平台
        target: _blank
        siteMonitor: https://ql.homehub.stream:8443
    - Transmission-桌面:
        icon: mdi-transmission-tower
        href: https://tr.homehub.stream:8443/transmission/web/index.html?devicetype=computer
        description: Transmission WebUI
        target: _blank
        siteMonitor: https://tr.homehub.stream:8443
    - Transmission-移动:
        icon: mdi-transmission-tower
        href: https://tr.homehub.stream:8443/transmission/web/index.mobile.html
        description: Transmission WebUI (移动端)
        target: _blank
        siteMonitor: https://tr.homehub.stream:8443
    - 服务器 IMPI:
        icon: mdi-monitor
        href: http://impi.ddns.net:60808/
        description: NAS IMPI管理面板
        target: _blank
        siteMonitor: http://impi.ddns.net:60808/
    - Aria2:
        icon: mdi-download-network
        href: https://aria.homehub.stream:8443/
        description: 下载工具 Aria2
        target: _blank
        siteMonitor: https://aria.homehub.stream:8443

- 内网服务:
    - Plex[内]:
        icon: mdi-plex
        href: http://192.168.31.8:32400/web/index.html#!/
        description: Plex 媒体服务器
        target: _blank
        siteMonitor: https://plex.homehub.stream:8443
    - 飞牛影视[内]:
        icon: mdi-movie-roll
        href: http://192.168.31.8:5666/v
        description: 飞牛OS 影视服务
        target: _blank
        siteMonitor: https://fn.homehub.stream:8443
    - Jellyfin[内]:
        icon: mdi-jellyfin
        href: http://192.168.31.8:28096/web/#/home.html
        description: 在线影视服务（Jellyfin）
        target: _blank
        siteMonitor: https://tv.homehub.stream:8443
    - MoviePilot[内]:
        icon: mdi-movie-open
        href: http://192.168.31.8:42720
        description: MoviePilot 影音管理
        target: _blank
        siteMonitor: https://mp.homehub.stream:8443
    - 飞牛OS[内]:
        icon: mdi-folder-network-outline
        href: http://192.168.31.8:5666
        description: 飞牛OS 主机管理
        target: _blank
        siteMonitor: https://fn.homehub.stream:8443
    - 1Panel[内]:
        icon: mdi-view-dashboard-variant
        href: http://192.168.31.8:17859/astral
        description: 1Panel 管理面板
        target: _blank
        siteMonitor: https://panel.homehub.stream:8443
    - qBittorrent[内]:
        icon: mdi-qbittorrent
        href: http://192.168.31.8:50581
        description: qBittorrent WebUI
        target: _blank
        siteMonitor: https://qb.homehub.stream:8443
    - qBittorrent-刷流[内]:
        icon: mdi-trending-up
        href: http://192.168.31.8:50582
        description: 刷流专用 qBittorrent
        target: _blank
        siteMonitor: https://qbit.homehub.stream:8443
    - qBittorrent-保种[内]:
        icon: mdi-seed
        href: http://192.168.31.8:50583
        description: 保种专用 qBittorrent
        target: _blank
        siteMonitor: https://keep.homehub.stream:8443
    - 青龙面板[内]:
        icon: mdi-script-text
        href: http://192.168.31.8:15700
        description: 青龙定时任务平台
        target: _blank
        siteMonitor: https://ql.homehub.stream:8443
    - Transmission-桌面[内]:
        icon: mdi-transmission-tower
        href: http://192.168.31.8:9091/transmission/web/index.html?devicetype=computer
        description: Transmission WebUI
        target: _blank
        siteMonitor: https://tr.homehub.stream:8443
    - Transmission-移动[内]:
        icon: mdi-transmission-tower
        href: http://192.168.31.8:9091/transmission/web/index.mobile.html
        description: Transmission WebUI (移动端)
        target: _blank
        siteMonitor: https://tr.homehub.stream:8443
    - 服务器 IMPI[内]:
        icon: mdi-monitor
        href: http://192.168.31.81
        description: NAS IMPI管理面板
        target: _blank
        siteMonitor: http://impi.ddns.net:60808/
    - 路由器[内]:
        icon: mdi-router-wireless
        href: http://192.168.31.1
        description: 路由器管理
        target: _blank
        siteMonitor: http://lab.homehub.stream:8443

- PT站点:
    - M-Team:
        icon: mdi-torrent
        href: https://kp.m-team.cc/browse
        description: 资源全面，做种健康，全球知名中文PT站
        target: _blank
        siteMonitor: https://kp.m-team.cc/browse
    - Audiences 观众:
        icon: mdi-torrent
        href: https://audiences.me/
        description: 界面现代，资源更新快，综合型站
        target: _blank
        siteMonitor: https://audiences.me/
    - HHCLUB 憨憨:
        icon: mdi-torrent
        href: https://hhanclub.top/
        description: 邀请制，高要求，优质种子集中地
        target: _blank
        siteMonitor: https://hhanclub.top/
    - 皇后音乐:
        icon: mdi-music
        href: https://open.cd/
        description: 华语圈最专业无损音乐站，品质极高
        target: _blank
        siteMonitor: https://open.cd/
    - 海豚音乐:
        icon: mdi-music
        href: https://dicmusic.com/torrents.php
        description: 欧美古典/独立音乐资源丰富，专注音质
        target: _blank
        siteMonitor: https://dicmusic.com/torrents.php
    - JPopsuki 音乐:
        icon: mdi-music
        href: https://jpopsuki.eu/torrents.php
        description: 全球顶级日音无损站，J-Pop/动漫原声首选
        target: _blank
        siteMonitor: https://jpopsuki.eu/torrents.php
    - PTTime:
        icon: mdi-torrent
        href: https://www.pttime.org/torrents.php
        description: 高清影视为主，老牌稳定，社区活跃
        target: _blank
        siteMonitor: https://www.pttime.org/torrents.php
    - HDTimePT 高清时间:
        icon: mdi-filmstrip
        href: https://hdtime.org/
        description: 专注高清影视，画质优秀，适合追剧
        target: _blank
        siteMonitor: https://hdtime.org/
    - BTSCHOOL:
        icon: mdi-torrent
        href: https://pt.btschool.club/torrents.php
        description: 多元资源，用户基数大，长期运营
        target: _blank
        siteMonitor: https://pt.btschool.club/torrents.php
    - PTSKIT:
        icon: mdi-torrent
        href: https://www.ptskit.org/torrents.php
        description: 综合资源，偏重电影与动画，稳定运行
        target: _blank
        siteMonitor: https://www.ptskit.org/torrents.php
    - 下水道PT:
        icon: mdi-torrent
        href: https://sewerpt.com/torrents.php
        description: 小众趣味站，资源较新，社区轻松
        target: _blank
        siteMonitor: https://sewerpt.com/torrents.php
    - 唐门PT:
        icon: mdi-torrent
        href: https://tmpt.top/torrents.php
        description: 中小型站，资源以国产为主，风格独特
        target: _blank
        siteMonitor: https://tmpt.top/torrents.php
    - HappyFappy:
        icon: mdi-torrent
        href: https://www.happyfappy.org/torrents.php
        description: 社区友好，资源覆盖广，适合新手
        target: _blank
        siteMonitor: https://www.happyfappy.org/torrents.php
    - 垃圾堆:
        icon: mdi-torrent
        href: https://pt.lajidui.top/torrents.php
        description: 名字戏谑，但资源实用，适合试用
        target: _blank
        siteMonitor: https://pt.lajidui.top/torrents.php
    - 肉丝:
        icon: mdi-torrent
        href: https://rousi.zip/torrents.php
        description: 小型站，资源偏冷门，适合探索
        target: _blank
        siteMonitor: https://rousi.zip/torrents.php
    - March:
        icon: mdi-torrent
        href: https://duckboobee.org/torrents.php
        description: 极小众站，资源稀少，趣味性强
        target: _blank
        siteMonitor: https://duckboobee.org/torrents.php

- 云服务:
    - 1Panel-Oracle:
        icon: mdi-view-dashboard-variant
        href: https://panel.eoysky.com/
        description: Oracle 主机管理面板
        target: _blank
        siteMonitor: https://panel.eoysky.com/
    - 青龙面板-Oracle:
        icon: mdi-script-text
        href: https://ql.astralwave.vip/login
        description: Oracle 青龙定时任务
        target: _blank
        siteMonitor: https://ql.astralwave.vip/login
    - Bitwarden:
        icon: mdi-lock
        href: https://vw.eoysky.com/
        description: Bitwarden 密码管理器
        target: _blank
        siteMonitor: https://vw.eoysky.com/
    - FreshRSS:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/freshrss.png
        href: https://admin.rsshub.in/
        description: 自托管 RSS 聚合器
        target: _blank
        siteMonitor: https://admin.rsshub.in
        widget:
          type: freshrss
          url: https://admin.rsshub.in
          username: astral
          password: Rain@8240
          fields:
            - subscriptions
            - unread
    - RSSHub:
        icon: mdi-rss-box
        href: https://rsshub.in/
        description: RSS 订阅服务
        target: _blank
        siteMonitor: https://rsshub.in/
    - Telegram API:
        icon: mdi-api
        href: https://tapi.eoysky.com/
        description: Telegram API 代理
        target: _blank
        siteMonitor: https://tapi.eoysky.com/
    - Telegram Proxy:
        icon: mdi-telegram-box
        href: https://tg.jiek.top/
        description: Telegram 代理服务
        target: _blank
        siteMonitor: https://tg.jiek.top/
    - Magichub:
        icon: mdi-account-star-outline
        href: https://magichub.top/
        description: 个人代理服务管理
        target: _blank
        siteMonitor: https://magichub.top/
    - Subconverter:
        icon: mdi-file-swap-outline
        href: https://sub.magichub.top/
        description: 代理订阅转换
        target: _blank
        siteMonitor: https://sub.magichub.top/
    - Dilyslyu.com:
        icon: mdi-creation
        href: https://dilyslyu.com/
        description: 个人主页 (Dilyslyu)
        target: _blank
        siteMonitor: https://dilyslyu.com/
    - Astralwave.io:
        icon: mdi-creation
        href: https://astralwave.io/
        description: 个人主页 (Astralwave)
        target: _blank
        siteMonitor: https://astralwave.io/
